site_name: SkyBlock Mod Wiki
site_url: https://sbmw.ca
site_description: >
  The SkyBlock Mod Wiki is a reference for the usage of modifications (mods for short) on Hypixel SkyBlock.
  It is intended to introduce new users to mods and be a reference to the variety of different features and settings each mod offers.
repo_name: ILikePlayingGames/SkyBlockModWiki
repo_url: https://github.com/ILikePlayingGames/SkyBlockModWiki
edit_uri: edit/main/docs
theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - navigation.top
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - toc:
      permalink: true
nav:
  - Home: 'index.md'
  - Tutorials:
      - How to Install Mods: 'tutorials/how-to-install-mods.md'
      - How to Find Crash Reports and Logs: 'tutorials/how-to-find-crash-reports-and-logs.md'
  - Mod Lists:
      - SkyBlock Mod List: 'mod-lists/skyblock-mod-list.md'
      - General Mod List: 'mod-lists/general-mod-list.md'
  - Tools:
      - Website List: 'tools/website-list.md'
      - Discord Bot List: 'tools/discord-bot-list.md'
  - Communities:
      - Discord Server List: 'communities/discord-server-list.md'
  - Mod Development Wiki: 'https://moddev.nea.moe'
extra_javascript:
  - 'js/open-in-new-tab.js'